name: Conventional Commits

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - uses: webiny/action-conventional-commits@1dc97face8fcf4db15ad186d34a1e44fdc5f0eb3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
