name: Conventional Commits

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - uses: webiny/action-conventional-commits@1dc97face8fcf4db15ad186d34a1e44fdc5f0eb3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
